### ISSUE TITLE
FUSES changed after flash and lost bootloader

### ISSUE THREAD

**Issue by Albert245** [lbernstone/ESP_AVRISP#1]
Hi, I'm following this project and use avrdude to flash with the cmd below:

> avrdude -c arduino -p m328p -P net:192.168.1.116:328 -U flash:w:SerialSample.ino.hex:i -v

And it's came this issue:

> avrdude: Version 6.4
>          Copyright (c) Brian Dean, http://www.bdmicro.com/
>          Copyright (c) Joerg Wunsch
> 
>          System wide configuration file is "C:\Program Files\AVRDUDE\avrdude.conf"
> 
>          Using Port                    : net:192.168.1.116:328
>          Using Programmer              : arduino
>          AVR Part                      : ATmega328P
>          Chip Erase delay              : 9000 us
>          PAGEL                         : PD7
>          BS2                           : PC2
>          RESET disposition             : dedicated
>          RETRY pulse                   : SCK
>          serial program mode           : yes
>          parallel program mode         : yes
>          Timeout                       : 200
>          StabDelay                     : 100
>          CmdexeDelay                   : 25
>          SyncLoops                     : 32
>          ByteDelay                     : 0
>          PollIndex                     : 3
>          PollValue                     : 0x53
>          Memory Detail                 :
> 
>                                   Block Poll               Page                       Polled
>            Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
>            ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
>            eeprom        65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
>            flash         65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
>            lfuse          0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
>            hfuse          0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
>            efuse          0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
>            lock           0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
>            calibration    0     0     0    0 no          1    1      0     0     0 0x00 0x00
>            signature      0     0     0    0 no          3    1      0     0     0 0x00 0x00
> 
>          Programmer Type : Arduino
>          Description     : Arduino
>          Hardware Version: 2
>          Firmware Version: 1.18
>          Topcard         : Unknown
>          Vtarget         : 0.0 V
>          Varef           : 0.0 V
>          Oscillator      : Off
>          SCK period      : 0.1 us
> 
> avrdude: AVR device initialized and ready to accept instructions
> 
> Reading | ################################################## | 100% 0.01s
> 
> avrdude: Device signature = 0x1e950f (probably lgt8fx328p)
> avrdude: safemode: lfuse reads as FF
> avrdude: safemode: hfuse reads as DE
> avrdude: safemode: efuse reads as FD
> avrdude: NOTE: "flash" memory has been specified, an erase cycle will be performed
>          To disable this feature, specify the -D option.
> avrdude: erasing chip
> avrdude: reading input file "SerialSample.ino.hex"
> avrdude: writing flash (1532 bytes):
> 
> Writing | ################################################## | 100% 0.49s
> 
> avrdude: 1532 bytes of flash written
> avrdude: verifying flash memory against SerialSample.ino.hex:
> avrdude: load data flash data from input file SerialSample.ino.hex:
> avrdude: input file SerialSample.ino.hex contains 1532 bytes
> avrdude: reading on-chip flash data:
> 
> Reading | ################################################## | 100% 0.34s
> 
> avrdude: verifying ...
> avrdude: verification error, first mismatch at byte 0x0000
>          0x00 != 0x0c
> avrdude: verification error; content mismatch
> 
> avrdude: safemode: lfuse reads as 0
> avrdude: safemode: hfuse reads as 0
> avrdude: safemode: efuse reads as 0
> avrdude: safemode: lfuse changed! Was ff, and is now 0
> Would you like this fuse to be changed back? [y/n] n
> avrdude: safemode: hfuse changed! Was de, and is now 0
> Would you like this fuse to be changed back? [y/n] n
> avrdude: safemode: efuse changed! Was fd, and is now 0
> Would you like this fuse to be changed back? [y/n] n
> avrdude: safemode: Fuses OK (E:00, H:00, L:00)
> 
> avrdude done.  Thank you.

I've checked that it lost the bootloader (or the bootloader went wrong) after flash and I have to re-burn bootloader.
Can anyone help me.

**Comment by lbernstone** [comment]
Absolutely the wrong place for this.  This code turns an esp32 into a programmer device.
